# src/config/config.yaml

data_dir: "./data"
model_name: "t5-small"
batch_size: 16
num_epochs: 3
learning_rate: 5e-5
max_source_length: 128
max_target_length: 128
checkpoint_dir: "./model/checkpoints"

# 데이터셋 설정 (필요 시)
dataset_name: "wmt16"
subset: "de-en"