name: t5_translation
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.10
  - pip
  - pip:
    - torch>=2.0.0
    - transformers>=4.0.0
    - datasets>=2.0.0
    - PyYAML>=6.0
    - tqdm>=4.0.0
    - numpy>=1.21.0
    - sentencepiece>=0.1.96